### ISSUE TITLE
[Feature request] Add A2I instrument format support

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/OPL3BankEditor#184] opened 2021-06-11 14:26 UTC

**Comment by Wohlstand** [comment] 2021-06-11 14:31
There is an actual work that got started at the [wip-adlibtracker](https://github.com/Wohlstand/OPL3BankEditor/tree/wip-adlibtracker) branch, the main challenge right now is to implement all compression algorithms used by these files. The source code is available and open, but it coded in Pascal (https://github.com/ijsf/at2). The fact the thing does use of a non-standard modified way of known compression algorithms, and therefore we need to port them from Pascal into C++ to get them being used.

**Comment by Wohlstand** [comment] 2021-06-11 14:34
But wait.... It's a duplicate of #170 !

**Closed** 2021-06-11 14:34 UTC
Labels: duplicate

**Comment by freq-mod** [comment] 2021-06-11 14:36
Oh, I'm sorry, I was in hurry and I haven't noticed it
